"""Exercise the Android shell runtime without a guest or root mount mutations."""
import hashlib
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
import tempfile
import textwrap
import unittest
import zipfile

REPO = Path(__file__).resolve().parents[1]
MODULE = REPO / 'modules/native-compat'
sys.path.insert(0, str(REPO / 'scripts'))
import dex2oat_cpu_policy as cpu_policy


def digest(data):
    return hashlib.sha256(data).hexdigest()


BUSYBOX = r'''#!/usr/bin/env python3
import fcntl, hashlib, json, os, pathlib, stat, subprocess, sys
args = sys.argv[1:]
command, args = args[0], args[1:]
metadata = json.loads(pathlib.Path(os.environ['HYPEROS_NATIVE_TEST_METADATA']).read_text())
if command == 'nsenter':
    args = args[args.index('--') + 1:]
    files = json.loads(os.environ.get('HYPEROS_NATIVE_TEST_FILES', '{}'))
    if args[0] == '/system/bin/ls':
        labels = json.loads(os.environ.get('HYPEROS_NATIVE_TEST_LABELS', '{}'))
        value = pathlib.Path(files.get(args[-1], args[-1])).stat()
        attrs = metadata.get(f'{value.st_dev}:{value.st_ino}', {})
        print(attrs.get('context', labels.get(args[-1], 'u:object_r:system_lib_file:s0')) + ' ' + args[-1]); sys.exit(0)
    args = [files.get(value, value) for value in args]
    os.execvp(args[0], args)
if command == 'sha256sum':
    if args and args[0] == '-c':
        for line in pathlib.Path(args[1]).read_text().splitlines():
            expected, name = line.split(None, 1)
            if hashlib.sha256(pathlib.Path(name.strip().lstrip('*')).read_bytes()).hexdigest() != expected:
                sys.exit(1)
        if os.environ.get('HYPEROS_NATIVE_TEST_TRACE'):
            with open(os.environ['HYPEROS_NATIVE_TEST_TRACE'], 'a') as output:
                output.write('assets-verified\n')
        sys.exit(0)
    try:
        for name in args:
            print(hashlib.sha256(pathlib.Path(name).read_bytes()).hexdigest() + '  ' + name)
    except OSError:
        sys.exit(1)
    sys.exit(0)
if command == 'stat' and args[0] == '-c':
    try:
        value = pathlib.Path(args[2]).stat()
        attrs = metadata.get(f'{value.st_dev}:{value.st_ino}', {})
        form = args[1]
        print(form.replace('%a', format(stat.S_IMODE(value.st_mode), 'o'))
              .replace('%s', str(value.st_size)).replace('%i', str(value.st_ino))
              .replace('%Y', str(int(value.st_mtime))).replace('%d', str(value.st_dev))
              .replace('%u:%g', attrs.get('owner', os.environ.get('HYPEROS_NATIVE_TEST_OWNER', f'{value.st_uid}:{value.st_gid}'))))
    except OSError:
        sys.exit(1)
    sys.exit(0)
if command == 'flock':
    try:
        fcntl.flock(int(args[-1]), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        sys.exit(1)
    sys.exit(0)
os.execvp(command, [command] + args)
'''


class NativeModuleRuntimeTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name).resolve()
        self.module = self.root / 'module'
        self.module.mkdir()
        for name in ('cache', 'state', 'sites'):
            (self.module / name).mkdir()
        for source in MODULE.iterdir():
            if source.is_file():
                shutil.copy2(source, self.module / source.name)
        # This shared asset is generated by the packager, outside the templates.
        (self.module / 'dex2oat-cpu-policy.sh').write_bytes(cpu_policy.policy_script())
        import package_native_module
        (self.module / 'features.tsv').write_bytes(package_native_module.module_files()['features.tsv'] + b'fixture\n')
        self.bin = self.root / 'bin'
        self.bin.mkdir()
        self.bb = self.bin / 'busybox'
        self.bb.write_text(BUSYBOX)
        self.bb.chmod(0o755)
        for name, body in {'pidof': 'exit 1', 'id': 'echo 0',
                           'getprop': 'case "$1" in ro.boot.hardware) echo ranchu;; '
                           'ro.mi.os.version.incremental) echo OS4.9.999.0.TEST;; '
                           'sys.boot_completed) echo 1;; esac'}.items():
            file = self.bin / name
            file.write_text('#!/bin/sh\n' + body + '\n')
            file.chmod(0o755)
        self.metadata = self.root / 'file-metadata.json'
        self.metadata.write_text('{}')
        for name, key in (('chcon', 'context'), ('chown', 'owner')):
            file = self.bin / name
            file.write_text('#!' + sys.executable + '\n' + textwrap.dedent('''
                import json, os, pathlib, sys
                path = pathlib.Path(os.environ['HYPEROS_NATIVE_TEST_METADATA'])
                values = json.loads(path.read_text()); target = pathlib.Path(sys.argv[2]).stat()
                key = f'{target.st_dev}:{target.st_ino}'
                values.setdefault(key, {})[ATTRIBUTE] = sys.argv[1]
                path.write_text(json.dumps(values))
            ''').replace('ATTRIBUTE', repr(key)))
            file.chmod(0o755)
        self.proc = self.root / 'proc'
        (self.proc / '1').mkdir(parents=True)
        (self.proc / '1/mountinfo').write_text('')
        (self.proc / 'sys/kernel/random').mkdir(parents=True)
        (self.proc / 'sys/kernel/random/boot_id').write_text('test-boot\n')
        self.packages = self.root / 'packages.xml'
        self.packages.write_text('<packages/>')
        self.target = self.root / 'libtest.so'
        self.original = b'header-original-instructions-and-tail'
        self.target.write_bytes(self.original)
        self.target.chmod(0o644)
        self.after = self.original.replace(b'original', b'patched!')
        self.profile('test', 'fixture', self.original, self.after, [(7, b'original', b'patched!')])
        (self.module / 'targets.tsv').write_text(f'early|system|fixture|{self.target}||libtest.so\n')
        self.environment = {**os.environ, 'PATH': str(self.bin) + os.pathsep + os.environ['PATH'],
                            'HYPEROS_NATIVE_BB': str(self.bb), 'HYPEROS_NATIVE_PROC': str(self.proc),
                            'HYPEROS_NATIVE_PACKAGES_XML': str(self.packages),
                            'HYPEROS_NATIVE_TEST_METADATA': str(self.metadata)}

    def file_metadata(self, path, **attributes):
        values = json.loads(self.metadata.read_text()); value = path.stat()
        values.setdefault(f'{value.st_dev}:{value.st_ino}', {}).update(attributes)
        self.metadata.write_text(json.dumps(values))

    def profile(self, name, feature, before, after, sites, legacy=(), append=False):
        rows = []
        directory = self.module / 'sites' / name
        directory.mkdir(exist_ok=True)
        for index, (offset, original, patched) in enumerate(sites):
            for suffix, data in (('before', original), ('after', patched)):
                (directory / f'{index:03d}.{suffix}').write_bytes(data)
            rows.append(f'{offset}|{len(original)}|sites/{name}/{index:03d}.before|sites/{name}/{index:03d}.after\n')
        (self.module / 'sites' / (name + '.tsv')).write_text(''.join(rows))
        row = '|'.join((digest(before), digest(after), ','.join(map(digest, legacy)), feature, name)) + '\n'
        path = self.module / 'profiles.tsv'
        path.write_text((path.read_text() if append and path.exists() else '') + row)

    def shell(self, body, *, check=True, overrides=''):
        script = 'MODDIR=' + shlex.quote(str(self.module)) + '\n'
        script += '. "$MODDIR/runtime.sh"\n' + overrides + '\n' + body
        return subprocess.run(['sh', '-c', script], env=self.environment, text=True,
                              capture_output=True, check=check)

    def safe_paths(self):
        return 'native_path() { case "$1" in ' + shlex.quote(str(self.root)) + '/*) return 0;; *) return 1;; esac; }'

    def app(self, body=None):
        apk = self.root / 'app.apk'
        with zipfile.ZipFile(apk, 'w') as archive:
            archive.writestr('lib/arm64-v8a/libtest.so', self.original if body is None else body)
        overrides = self.safe_paths() + '\n'
        overrides += 'pm() { printf "package:%s\\n" ' + shlex.quote(str(apk)) + '; }\n'
        overrides += 'dumpsys() { printf "nativeLibraryDir=%s\\n" ' + shlex.quote(str(self.root)) + '; }\n'
        return apk, overrides

    def customize(self, registry, *, check=True):
        self.checksums()
        content = (MODULE / 'customize.sh').read_text().replace(
            '/data/adb/ksu/bin/busybox', str(self.bb)).replace('/data/adb/modules', str(registry))
        helpers = ('ARCH=arm64\nMODPATH=' + shlex.quote(str(self.module)) + '\n'
                   'abort() { echo "$*" >&2; exit 1; }\nui_print() { :; }\n'
                   'set_perm_recursive() { :; }\nset_perm() { :; }\n')
        return subprocess.run(['sh', '-c', helpers + content], env=self.environment,
                              text=True, capture_output=True, check=check)

    def checksums(self):
        files = sorted(path for path in self.module.rglob('*') if path.is_file()
                       and 'cache' not in path.relative_to(self.module).parts
                       and 'state' not in path.relative_to(self.module).parts
                       and path.name != 'SHA256SUMS')
        (self.module / 'SHA256SUMS').write_text(''.join(
            digest(path.read_bytes()) + '  ' + str(path.relative_to(self.module)) + '\n'
            for path in files))

    def cpu_fixture(self, online='0-5', possible='0-5', count=6, boot='1'):
        self.cpu = self.root / 'cpu'
        self.cpu.mkdir()
        (self.cpu / 'online').write_text(online)
        (self.cpu / 'possible').write_text(possible)
        self.cpu_properties = self.root / 'cpu-properties.json'
        self.cpu_properties.write_text(json.dumps({
            'ro.boot.hardware': 'ranchu', 'ro.mi.os.version.name': 'OS4.0',
            'ro.mi.os.version.incremental': 'OS4.99.TEST', 'sys.boot_completed': boot,
            'dalvik.vm.default-dex2oat-cpu-set': '0,1,2,3,4,5,6,7',
            'dalvik.vm.dex2oat-threads': '2', 'dalvik.vm.background-dex2oat-threads': '99'}))
        self.cpu_trace = self.root / 'cpu-trace'
        self.cpu_trace.write_text('')
        for name, body in {
            'getprop': '''import json, os, sys
print(json.load(open(os.environ['CPU_TEST_PROPERTIES'])).get(sys.argv[1], ''))''',
            'setprop': '''import json, os, sys
p = os.environ['CPU_TEST_PROPERTIES']; values = json.load(open(p)); values[sys.argv[1]] = sys.argv[2]
with open(p, 'w') as output: json.dump(values, output)
with open(os.environ['HYPEROS_NATIVE_TEST_TRACE'], 'a') as output: output.write('write:' + sys.argv[1] + '=' + sys.argv[2] + '\\n')''',
            'getconf': '''import os
print(os.environ['CPU_TEST_COUNT'])''',
        }.items():
            path = self.bin / name
            path.write_text('#!' + sys.executable + '\n' + body + '\n')
            path.chmod(0o755)
        self.environment.update(DEX2OAT_CPU_ROOT=str(self.cpu), CPU_TEST_COUNT=str(count),
                                CPU_TEST_PROPERTIES=str(self.cpu_properties),
                                HYPEROS_NATIVE_TEST_TRACE=str(self.cpu_trace))
        # Preserve real guard, checksums and service lock. Only native bind work
        # and periodic observation are replaced; CPU policy remains the real sh.
        return textwrap.dedent('''
            native_reconcile() { echo "reconcile:$1" >> "$HYPEROS_NATIVE_TEST_TRACE"; }
            native_cleanup() { echo cleanup >> "$HYPEROS_NATIVE_TEST_TRACE"; }
            native_package_token() { echo stable; }
            sleep() { touch "$MODDIR/disable"; }
        ''')

    def rear_properties(self, **changes):
        values = {'persist.sys.multi_display_type': '6',
                  'persist.sys.secondary_builtin_display_id': '2',
                  'persist.sys.dual_screen_cover_mode_enable': 'true',
                  'ro.boot.qemu.external.displays': '2,1000,700,300,0'}
        values.update(changes)
        return 'getprop() { case "$1" in\n' + '\n'.join(
            shlex.quote(key) + ') printf "%s\\n" ' + shlex.quote(value) + ';;'
            for key, value in values.items()) + '\nesac; }\n'

    def composer_chain(self):
        final = self.after.replace(b'tail', b'done')
        self.profile('composer', 'composer', self.original, self.after,
                     [(7, b'original', b'patched!')])
        self.profile('rear', 'rear-display', self.after, final,
                     [(len(self.after) - 4, b'tail', b'done')], append=True)
        (self.module / 'targets.tsv').write_text(
            f'early|system|composer|{self.target}||libtest.so\n'
            f'early|system|rear-display|{self.target}||libtest.so\n')
        return final

    def mount_fixture(self, executable=True, pids=('1',)):
        target = '/vendor/bin/hw/audited-hwc-service' if executable else str(self.target)
        self.mount_payload = self.module / 'cache/payload.so'
        self.mount_payload.write_bytes(self.after)
        self.mount_payload.chmod(0o755 if executable else 0o644)
        self.target.chmod(0o755 if executable else 0o644)
        feature = 'composer' if executable else 'fixture'
        self.profile('mount', feature, self.original, self.after,
                     [(7, b'original', b'patched!')])
        (self.module / 'targets.tsv').write_text(f'early|system|{feature}|{target}||test-native\n')
        label = 'u:object_r:hal_graphics_composer_default_exec:s0' if executable else 'u:object_r:system_lib_file:s0'
        self.environment.update(HYPEROS_NATIVE_TEST_FILES=json.dumps({target: str(self.target)}),
                                HYPEROS_NATIVE_TEST_LABELS=json.dumps({target: label, str(self.mount_payload): label}),
                                HYPEROS_NATIVE_TEST_OWNER='0:0')
        states = self.root / 'mount-state'; states.mkdir()
        for pid in pids:
            (self.proc / pid).mkdir(exist_ok=True)
            (self.proc / pid / 'mountinfo').write_text('')
            (states / pid).write_text(digest(self.original) + '\n')
        self.mount_trace = self.root / 'mount-trace'
        overrides = 'STATE=' + shlex.quote(str(states)) + '\nMARKER=' + shlex.quote(str(self.mount_trace)) + '\n'
        overrides += 'TARGET=' + shlex.quote(target) + '\nPAYLOAD=' + shlex.quote(str(self.mount_payload)) + '\n'
        overrides += 'INITIAL=' + digest(self.original) + '\nFINAL=' + digest(self.after) + '\n'
        overrides += 'native_pids() { printf "%s\\n" ' + ' '.join(map(shlex.quote, pids)) + '; }\n'
        overrides += 'native_ns_hash() { cat "$STATE/$1"; }\n'
        overrides += textwrap.dedent('''
            native_ns() {
                local pid=$1; shift
                if [ "$1" = "$BB" ] && [ "$2" = mount ]; then
                    shift 2
                    printf '%s:%s\\n' "$pid" "$*" >> "$MARKER"
                    if [ "$2" = bind ]; then
                        printf '%s\\n' "$FINAL" > "$STATE/$pid"
                        printf '1 0 1:1 %s %s rw,nosuid,nodev - ext4 userdata rw,seclabel\\n' "$PAYLOAD" "$TARGET" > "$PROC/$pid/mountinfo"
                    else
                        case ",$2," in *,suid,*) flags=ro,nodev;; *) flags=ro,nosuid,nodev;; esac
                        [ "$pid" != "${NATIVE_TEST_BAD_FLAGS_PID:-}" ] || flags=ro,nosuid,nodev,noexec
                        printf '1 0 1:1 %s %s %s - ext4 userdata rw,seclabel\\n' "$PAYLOAD" "$TARGET" "$flags" > "$PROC/$pid/mountinfo"
                    fi
                elif [ "$1" = "$BB" ] && [ "$2" = umount ]; then
                    printf '%s:rollback\\n' "$pid" >> "$MARKER"
                    printf '%s\\n' "$INITIAL" > "$STATE/$pid"
                    : > "$PROC/$pid/mountinfo"
                else "$BB" nsenter -t "$pid" -m -- "$@"; fi
            }
        ''')
        command = 'native_mount ' + ' '.join(map(shlex.quote, (target, str(self.mount_payload), '',
                                             digest(self.original), digest(self.after))))
        return command, overrides, target

    def test_rear_display_requires_semantic_capability_and_matching_boot_panel(self):
        self.shell('native_eligible rear-display', overrides=self.rear_properties())
        self.shell('native_eligible rear-display', overrides=self.rear_properties(**{
            'persist.sys.secondary_builtin_display_id': '3',
            'ro.boot.qemu.external.displays': '1,512,512,160,0,3,800,600,200,7'}))
        invalid = ({key: ''} for key in ('persist.sys.multi_display_type',
                   'persist.sys.secondary_builtin_display_id', 'persist.sys.dual_screen_cover_mode_enable',
                   'ro.boot.qemu.external.displays'))
        cases = list(invalid) + [
            {'persist.sys.multi_display_type': '0'},
            {'persist.sys.dual_screen_cover_mode_enable': 'false'},
            {'persist.sys.secondary_builtin_display_id': '0'},
            {'persist.sys.secondary_builtin_display_id': '2x'}]
        cases.extend({'ro.boot.qemu.external.displays': value} for value in
                     ('1,1000,700,300,0', '2,0,700,300,0', '2,1000,700,0,0',
                      '2,1000,700,300,-1', '2,1000,700,300,x', '2,1000,700,300',
                      '2,1000,700,300,0\n3,800,600,200,0',
                      '2,1000,700,300,0,2,800,600,200,0',
                      '2,1000,700,300,0,02,800,600,200,0'))
        for values in cases:
            with self.subTest(values=values):
                self.shell('! native_eligible rear-display', overrides=self.rear_properties(**values))
        self.shell('native_eligible composer; native_eligible flutter', overrides='getprop() { :; }')

    def test_pad_skips_rear_chain_while_phone_keeps_verified_back_panel(self):
        final = self.composer_chain()
        trace = self.root / 'feature-binds'
        overrides = self.safe_paths() + '\n'
        overrides += 'native_mount() { cp "$2" "$1"; printf "%s\\n" "$5" >> ' + shlex.quote(str(trace)) + '; }\n'
        self.shell('native_reconcile early', overrides=overrides)
        self.assertEqual(self.target.read_bytes(), self.after)
        self.assertEqual(trace.read_text(), digest(self.after) + '\n')
        status = (self.module / 'state/status.tsv').read_text()
        self.assertIn('composer|' + str(self.target) + '|ready|verified-bind\n', status)
        self.assertIn('rear-display|' + str(self.target) + '|skipped|device-capability-unavailable\n', status)
        self.shell('native_reconcile late', overrides=overrides)
        self.assertNotIn('rear-display|' + str(self.target) + '|pending|',
                         (self.module / 'state/status.tsv').read_text())
        self.target.write_bytes(self.original); trace.unlink()
        self.shell('native_reconcile early', overrides=overrides + self.rear_properties())
        self.assertEqual(self.target.read_bytes(), final)
        self.assertEqual(trace.read_text(), digest(self.after) + '\n' + digest(final) + '\n')
        self.assertIn('rear-display|' + str(self.target) + '|ready|verified-bind\n',
                      (self.module / 'state/status.tsv').read_text())

    def test_rear_terminal_output_requires_device_capability_for_composer_chain(self):
        final = self.composer_chain()
        body = 'native_superseded_output composer ' + digest(final) + ' ' + shlex.quote(str(self.target))
        self.shell('! ' + body)
        self.shell(body, overrides=self.rear_properties())

    def test_verified_composer_bind_clears_nosuid_only_on_its_single_file_mount(self):
        command, overrides, target = self.mount_fixture()
        self.shell(command, overrides=overrides)
        self.assertEqual(self.mount_payload.stat().st_mode & 0o7777, 0o755)
        self.assertEqual(self.target.read_bytes(), self.original)
        self.assertIn('1:-o remount,bind,ro,suid,nodev,exec ' + target + '\n', self.mount_trace.read_text())
        self.assertIn(' ro,nodev - ext4 ', (self.proc / '1/mountinfo').read_text())

    def test_verified_root_shell_composer_preserves_sdk_vendor_ownership(self):
        command, overrides, target = self.mount_fixture()
        self.environment['HYPEROS_NATIVE_TEST_OWNER'] = '0:2000'
        self.shell(command, overrides=overrides)
        self.assertIn('1:-o remount,bind,ro,suid,nodev,exec ' + target + '\n', self.mount_trace.read_text())
        self.assertEqual(self.mount_payload.stat().st_mode & 0o7777, 0o755)

    def test_composer_rejects_other_owner_groups_and_payload_owner_mismatch(self):
        command, overrides, _ = self.mount_fixture()
        for target_owner, payload_owner in (('1000:2000', '1000:2000'),
                                            ('0:1000', '0:1000'),
                                            ('0:2000', '0:0'), ('0:0', '0:2000')):
            with self.subTest(target_owner=target_owner, payload_owner=payload_owner):
                self.file_metadata(self.target, owner=target_owner)
                self.file_metadata(self.mount_payload, owner=payload_owner)
                result = self.shell(command, overrides=overrides, check=False)
                self.assertNotEqual(result.returncode, 0)
                self.assertFalse(self.mount_trace.exists())
                self.assertEqual((self.proc / '1/mountinfo').read_text(), '')

    def test_library_bind_retains_nosuid(self):
        command, overrides, target = self.mount_fixture(executable=False)
        self.shell(command, overrides=overrides)
        self.assertIn('1:-o remount,bind,ro,nosuid,nodev ' + target + '\n', self.mount_trace.read_text())
        self.assertIn(' ro,nosuid,nodev - ext4 ', (self.proc / '1/mountinfo').read_text())

    def test_composer_transition_exception_rejects_untrusted_metadata(self):
        command, overrides, target = self.mount_fixture()
        for invalid in ('mode', 'target-mode', 'set-id', 'label', 'payload-label', 'owner', 'bytes', 'catalog'):
            with self.subTest(invalid=invalid):
                before = self.mount_payload.read_bytes()
                labels = self.environment['HYPEROS_NATIVE_TEST_LABELS']
                owner = self.environment['HYPEROS_NATIVE_TEST_OWNER']
                catalog = (self.module / 'targets.tsv').read_text()
                if invalid == 'mode': self.mount_payload.chmod(0o644)
                elif invalid == 'target-mode': self.target.chmod(0o644)
                elif invalid == 'set-id': self.mount_payload.chmod(0o4755)
                elif invalid == 'label':
                    self.environment['HYPEROS_NATIVE_TEST_LABELS'] = json.dumps({target: 'u:object_r:system_file:s0'})
                elif invalid == 'payload-label':
                    self.environment['HYPEROS_NATIVE_TEST_LABELS'] = json.dumps({target: 'u:object_r:hal_graphics_composer_default_exec:s0'})
                elif invalid == 'owner': self.environment['HYPEROS_NATIVE_TEST_OWNER'] = '1000:1000'
                elif invalid == 'bytes': self.mount_payload.write_bytes(b'unknown native')
                elif invalid == 'catalog': (self.module / 'targets.tsv').write_text('')
                result = self.shell(command, overrides=overrides, check=False)
                self.assertNotEqual(result.returncode, 0)
                self.assertFalse(self.mount_trace.exists())
                self.assertEqual((self.proc / '1/mountinfo').read_text(), '')
                self.mount_payload.write_bytes(before); self.mount_payload.chmod(0o755); self.target.chmod(0o755)
                self.environment['HYPEROS_NATIVE_TEST_LABELS'] = labels
                self.environment['HYPEROS_NATIVE_TEST_OWNER'] = owner
                (self.module / 'targets.tsv').write_text(catalog)

    def test_inherited_nosuid_or_noexec_rolls_back_all_new_composer_binds(self):
        command, overrides, _ = self.mount_fixture(pids=('1', '2'))
        self.shell(command, overrides=overrides + '\nNATIVE_TEST_BAD_FLAGS_PID=2\n', check=False)
        trace = self.mount_trace.read_text()
        self.assertIn('2:rollback\n', trace); self.assertIn('1:rollback\n', trace)
        for pid in ('1', '2'):
            self.assertEqual((self.proc / pid / 'mountinfo').read_text(), '')

    def test_composer_mountinfo_rejects_each_transition_blocker_independently(self):
        _, _, target = self.mount_fixture()
        line = f'1 0 1:1 {self.mount_payload} {target} FLAGS - ext4 userdata rw,seclabel\n'
        body = 'native_mount_flags 1 ' + shlex.quote(target) + ' remount,bind,ro,suid,nodev,exec'
        for flags in ('ro,nosuid,nodev', 'ro,nodev,noexec', 'rw,nodev'):
            with self.subTest(flags=flags):
                (self.proc / '1/mountinfo').write_text(line.replace('FLAGS', flags))
                self.shell('! ' + body)
        (self.proc / '1/mountinfo').write_text(line.replace('FLAGS', 'ro,nodev'))
        self.shell(body)

    def test_cpu_helper_early_and_late_use_verified_assets_and_actual_topology(self):
        overrides = self.cpu_fixture()
        self.checksums()
        self.shell('native_start early', overrides=overrides)
        early = json.loads(self.cpu_properties.read_text())
        self.assertEqual(early['dalvik.vm.default-dex2oat-cpu-set'], '0,1,2,3,4,5')
        self.assertEqual(early['dalvik.vm.dex2oat-threads'], '2')
        self.assertEqual(early['dalvik.vm.background-dex2oat-threads'], '6')
        self.assertNotIn('dalvik.vm.dex2oat-cpu-set', early)
        events = self.cpu_trace.read_text().splitlines()
        self.assertEqual(events[0], 'assets-verified')
        self.assertTrue(events[1].startswith('write:'))
        self.assertEqual(events[-1], 'reconcile:early')

        # Late boot can publish new OEM values and a different online subset.
        early['dalvik.vm.default-dex2oat-cpu-set'] = '0,1,2,3,4,5,6,7'
        self.cpu_properties.write_text(json.dumps(early))
        (self.cpu / 'online').write_text('0,2,5')
        self.cpu_trace.write_text('')
        self.shell('native_service', overrides=overrides)
        late = json.loads(self.cpu_properties.read_text())
        self.assertEqual(late['dalvik.vm.default-dex2oat-cpu-set'], '0,2,5')
        self.assertEqual(late['dalvik.vm.background-dex2oat-threads'], '3')
        self.assertEqual(late['dalvik.vm.dex2oat-threads'], '2')
        events = self.cpu_trace.read_text().splitlines()
        first_write = next(i for i, line in enumerate(events) if line.startswith('write:'))
        self.assertIn('assets-verified', events[:first_write])
        self.assertLess(first_write, events.index('reconcile:late'))
        self.assertEqual(events[-1], 'cleanup')
        self.assertFalse((self.module / 'service.lock').exists())
        self.assertEqual(self.target.read_bytes(), self.original)

    def test_cpu_helper_is_skipped_for_blocked_or_unowned_module_paths(self):
        overrides = self.cpu_fixture()
        self.checksums()
        original = self.cpu_properties.read_bytes()
        alias = self.root / 'module-alias'; alias.symlink_to(self.module, target_is_directory=True)
        for entrypoint in ('native_start early', 'native_service'):
            for flag in ('disable', 'remove'):
                with self.subTest(entrypoint=entrypoint, flag=flag):
                    (self.module / flag).touch()
                    self.cpu_trace.write_text('')
                    self.shell(entrypoint, overrides=overrides)
                    self.assertEqual(self.cpu_properties.read_bytes(), original)
                    self.assertEqual(self.cpu_trace.read_text(), '')
                    (self.module / flag).unlink()
            self.cpu_trace.write_text('')
            result = self.shell('MODDIR=' + shlex.quote(str(alias)) + '\n' + entrypoint,
                                overrides=overrides, check=False)
            self.assertNotEqual(result.returncode, 0)
            self.assertEqual(self.cpu_properties.read_bytes(), original)
            self.assertEqual(self.cpu_trace.read_text(), '')
        self.assertEqual(self.target.read_bytes(), self.original)

    def test_cpu_helper_cannot_execute_with_invalid_checked_assets(self):
        overrides = self.cpu_fixture()
        self.checksums()
        original = self.cpu_properties.read_bytes()
        marker = self.root / 'forbidden-cpu-script'
        for name in ('dex2oat-cpu-policy.sh', 'module.prop', 'profiles.tsv'):
            saved = (self.module / name).read_bytes()
            with self.subTest(asset=name):
                (self.module / name).write_text('touch ' + shlex.quote(str(marker)) + '\n')
                for entrypoint in ('native_start early', 'native_service'):
                    self.cpu_trace.write_text('')
                    result = self.shell(entrypoint, overrides=overrides, check=False)
                    self.assertNotEqual(result.returncode, 0)
                    self.assertEqual(self.cpu_properties.read_bytes(), original)
                    self.assertEqual(self.cpu_trace.read_text(), '')
                    self.assertFalse(marker.exists())
                (self.module / name).write_bytes(saved)
        self.assertEqual(self.target.read_bytes(), self.original)

    def test_cpu_helper_respects_blocking_flags_published_with_boot_completion(self):
        overrides = self.cpu_fixture(boot='0')
        self.checksums()
        original = self.cpu_properties.read_bytes()
        boot_complete = self.bin / 'complete-boot'
        boot_complete.write_text('#!' + sys.executable + '''
import json, os
p = os.environ['CPU_TEST_PROPERTIES']; values = json.load(open(p)); values['sys.boot_completed'] = '1'
with open(p, 'w') as output: json.dump(values, output)
''')
        boot_complete.chmod(0o755)
        for flag in ('disable', 'remove'):
            with self.subTest(flag=flag):
                self.cpu_properties.write_bytes(original)
                self.cpu_trace.write_text('')
                extra = '\nsleep() { touch "$MODDIR/' + flag + '"; complete-boot; }'
                self.shell('native_service', overrides=overrides + extra)
                events = self.cpu_trace.read_text().splitlines()
                self.assertFalse(any(line.startswith(('write:', 'reconcile:')) for line in events))
                (self.module / flag).unlink()
        self.assertFalse((self.module / 'service.lock').exists())

    def test_cpu_helper_revalidates_assets_after_waiting_for_boot(self):
        overrides = self.cpu_fixture(boot='0')
        self.checksums()
        marker = self.root / 'forbidden-after-boot'
        complete = self.bin / 'complete-corrupt-boot'
        complete.write_text('#!' + sys.executable + '''
import json, os, pathlib
p = os.environ['CPU_TEST_PROPERTIES']; values = json.load(open(p)); values['sys.boot_completed'] = '1'
with open(p, 'w') as output: json.dump(values, output)
pathlib.Path(os.environ['CPU_TEST_HELPER']).write_text(os.environ['CPU_TEST_CORRUPT'])
''')
        complete.chmod(0o755)
        self.environment.update(CPU_TEST_HELPER=str(self.module / 'dex2oat-cpu-policy.sh'),
                                CPU_TEST_CORRUPT='touch ' + shlex.quote(str(marker)) + '\n')
        bounded = '''
cpu_sleep_calls=0
sleep() {
    cpu_sleep_calls=$((cpu_sleep_calls + 1))
    if [ "$cpu_sleep_calls" = 1 ]; then complete-corrupt-boot
    else touch "$MODDIR/disable"; fi
}
'''
        result = self.shell('native_service', overrides=overrides + bounded, check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertFalse(marker.exists())
        self.assertFalse(any(line.startswith(('write:', 'reconcile:'))
                             for line in self.cpu_trace.read_text().splitlines()))
        self.assertFalse((self.module / 'service.lock').exists())

    def test_shell_syntax_and_standard_module_entrypoints(self):
        for filename in ('runtime.sh', 'post-fs-data.sh', 'service.sh', 'customize.sh'):
            with self.subTest(filename=filename):
                subprocess.run(['sh', '-n', str(MODULE / filename)], check=True, capture_output=True)
        self.assertIn('SKIPMOUNT=true', (MODULE / 'customize.sh').read_text())
        self.assertIn('id=hyperos_avd_native_compat\n', (MODULE / 'module.prop').read_text())

    def test_os4_hardware_guard_has_no_avd_or_exact_firmware_gate(self):
        self.shell('native_guard')
        self.shell('getprop() { case "$1" in ro.boot.hardware) echo ranchu;; *) echo 4.1.999;; esac; }; native_guard')
        self.shell('getprop() { echo Pixel; }; ! native_guard')
        self.shell('getprop() { case "$1" in ro.boot.hardware) echo ranchu;; *) echo OS3.1;; esac; }; ! native_guard')
        runtime = (MODULE / 'runtime.sh').read_text()
        self.assertNotIn('ro.boot.qemu.avd_name', runtime)
        self.assertNotIn('OS4.0.', runtime)

    def test_customizer_preserves_known_core_feature_choices(self):
        registry = self.root / 'modules'
        prior = registry / 'hyperos_avd_native_compat'
        prior.mkdir(parents=True)
        (prior / 'features.disabled').write_text('fixture\n')
        self.customize(registry)
        self.assertEqual((self.module / 'features.disabled').read_text(), 'fixture\n')
        self.assertEqual((prior / 'features.disabled').read_text(), 'fixture\n')

    def test_customizer_inherits_legacy_choices_without_changing_flags(self):
        registry = self.root / 'modules'
        for identifier, flag in (('hyperos_avd_flutter_render', 'disable'),
                                 ('hyperos_avd_assistant_mgl', 'remove')):
            folder = registry / identifier
            folder.mkdir(parents=True)
            (folder / flag).write_text('preserve')
        self.customize(registry)
        self.assertEqual((self.module / 'features.disabled').read_text(), 'assistant\nflutter\n')
        self.assertEqual((registry / 'hyperos_avd_flutter_render/disable').read_text(), 'preserve')
        self.assertEqual((registry / 'hyperos_avd_assistant_mgl/remove').read_text(), 'preserve')

    def test_customizer_empty_core_choices_are_authoritative_over_legacy_flags(self):
        registry = self.root / 'modules'
        prior = registry / 'hyperos_avd_native_compat'
        prior.mkdir(parents=True)
        (prior / 'features.disabled').write_text('')
        legacy = registry / 'hyperos_avd_flutter_render'
        legacy.mkdir()
        (legacy / 'disable').write_text('preserve')
        self.customize(registry)
        self.assertEqual((self.module / 'features.disabled').read_text(), '')
        self.assertEqual((legacy / 'disable').read_text(), 'preserve')

    def test_customizer_rejects_unknown_or_aliased_prior_choices(self):
        registry = self.root / 'modules'
        prior = registry / 'hyperos_avd_native_compat'
        prior.mkdir(parents=True)
        choices = prior / 'features.disabled'
        choices.write_text('unknown-feature\n')
        self.assertNotEqual(self.customize(registry, check=False).returncode, 0)
        self.assertEqual(choices.read_text(), 'unknown-feature\n')
        choices.unlink()
        unrelated = self.root / 'unrelated-choices'
        unrelated.write_text('fixture\n')
        choices.symlink_to(unrelated)
        self.assertNotEqual(self.customize(registry, check=False).returncode, 0)
        self.assertEqual(unrelated.read_text(), 'fixture\n')

    def test_customizer_prefers_surviving_staged_choices_over_active(self):
        registry = self.root / 'modules'
        prior = registry / 'hyperos_avd_native_compat'
        prior.mkdir(parents=True)
        (prior / 'features.disabled').write_text('fixture\n')
        # An empty pending choice file means the user enabled every feature.
        (self.module / 'features.disabled').write_text('')
        self.customize(registry)
        self.assertEqual((self.module / 'features.disabled').read_text(), '')
        self.assertEqual((prior / 'features.disabled').read_text(), 'fixture\n')

    def test_customizer_prefers_verified_separate_pending_choices(self):
        registry = self.root / 'modules'
        prior = registry / 'hyperos_avd_native_compat'
        prior.mkdir(parents=True)
        (prior / 'features.disabled').write_text('fixture\n')
        pending = Path(str(registry) + '_update') / 'hyperos_avd_native_compat'
        pending.mkdir(parents=True)
        properties = pending / 'module.prop'
        properties.write_text('id=hyperos_avd_native_compat\nauthor=HyperOS-AVD\n')
        (pending / 'SHA256SUMS').write_text(digest(properties.read_bytes()) + '  module.prop\n')
        (pending / 'features.disabled').write_text('')
        self.customize(registry)
        self.assertEqual((self.module / 'features.disabled').read_text(), '')
        self.assertEqual((prior / 'features.disabled').read_text(), 'fixture\n')

    def test_asset_checksums_precede_target_changes(self):
        self.checksums()
        self.shell('native_assets')
        with (self.module / 'profiles.tsv').open('a') as output:
            output.write('unexpected\n')
        self.shell('! native_assets')
        self.assertEqual(self.target.read_bytes(), self.original)

    def test_patch_copy_checks_exact_bytes_and_final_hash(self):
        result = self.shell('native_prepare ' + shlex.quote(str(self.target)) + ' fixture ' + digest(self.original))
        payload = Path(result.stdout.strip())
        self.assertEqual(payload.read_bytes(), self.after)
        self.assertEqual(self.target.read_bytes(), self.original)
        self.assertEqual(payload.stat().st_mode & 0o777, 0o644)
        self.assertFalse(list((self.module / 'cache').glob('*.next.*')))

    def test_patch_cache_preserves_and_keys_original_uid_gid(self):
        self.target.chmod(0o755)
        self.file_metadata(self.target, owner='0:0', context='u:object_r:hal_graphics_composer_default_exec:s0')
        body = 'native_prepare ' + shlex.quote(str(self.target)) + ' fixture ' + digest(self.original)
        root_payload = Path(self.shell(body).stdout.strip())
        self.assertIn('-755-0-0-', root_payload.name)
        self.file_metadata(self.target, owner='0:2000')
        shell_payload = Path(self.shell(body).stdout.strip())
        self.assertIn('-755-0-2000-', shell_payload.name)
        self.assertNotEqual(shell_payload, root_payload)
        self.assertEqual(shell_payload.read_bytes(), self.after)
        self.assertEqual(root_payload.read_bytes(), self.after)
        before_inode = shell_payload.stat().st_ino
        reused = Path(self.shell(body).stdout.strip())
        self.assertEqual(reused, shell_payload)
        self.assertEqual(reused.stat().st_ino, before_inode)
        self.assertEqual(self.shell('native_ns 1 "$BB" stat -c %u:%g ' + shlex.quote(str(reused))).stdout.strip(), '0:2000')
        self.assertEqual(self.target.read_bytes(), self.original)

    def test_patch_cache_refuses_metadata_drift_without_repairing_a_published_inode(self):
        self.target.chmod(0o755)
        label = 'u:object_r:hal_graphics_composer_default_exec:s0'
        self.file_metadata(self.target, owner='0:2000', context=label)
        body = 'native_prepare ' + shlex.quote(str(self.target)) + ' fixture ' + digest(self.original)
        payload = Path(self.shell(body).stdout.strip())
        inode = payload.stat().st_ino
        for invalid in ('mode', 'owner', 'context'):
            with self.subTest(invalid=invalid):
                if invalid == 'mode': payload.chmod(0o644)
                elif invalid == 'owner': self.file_metadata(payload, owner='0:0')
                else: self.file_metadata(payload, context='u:object_r:system_file:s0')
                result = self.shell(body, check=False)
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(result.stdout, '')
                self.assertEqual(payload.stat().st_ino, inode)
                self.assertEqual(payload.read_bytes(), self.after)
                self.assertEqual(self.target.read_bytes(), self.original)
                self.assertFalse(list((self.module / 'cache').glob('candidate.next.*')))
                if invalid == 'mode': self.assertEqual(payload.stat().st_mode & 0o777, 0o644)
                payload.chmod(0o755); self.file_metadata(payload, owner='0:2000', context=label)

    def test_legacy_input_with_preexisting_sites_is_supported(self):
        old = self.original.replace(b'original', b'patched!')
        final = old.replace(b'tail', b'done')
        self.profile('legacy', 'fixture', self.original, final,
                     [(7, b'original', b'patched!'), (len(old) - 4, b'tail', b'done')], legacy=(old,))
        self.target.write_bytes(old)
        result = self.shell('native_prepare ' + shlex.quote(str(self.target)) + ' fixture ' + digest(old))
        self.assertEqual(Path(result.stdout.strip()).read_bytes(), final)

    def test_bad_site_or_expected_output_preserves_input(self):
        (self.module / 'sites/test/000.before').write_bytes(b'wrong!!!')
        result = self.shell('native_prepare ' + shlex.quote(str(self.target)) + ' fixture ' + digest(self.original), check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(self.target.read_bytes(), self.original)
        self.assertFalse(list((self.module / 'cache').glob('candidate.next.*')))

    def test_private_native_path_allowlist(self):
        for path in ('/data/app/~~abc/com.miui.home-def/lib/arm64/libtest.so',
                     '/data/app-lib/MIUIWeather/arm64/libtest.so'):
            self.shell('native_private_target ' + shlex.quote(path))
        for path in ('/product/app/Weather/lib/arm64/libtest.so', '/data/app/libtest.so',
                     '/data/app/../../system/lib/arm64/libtest.so', '/data/app/x/lib/arm64/a/b.so'):
            self.shell('! native_private_target ' + shlex.quote(path))

    def package_dump(self, content):
        path = self.root / 'package-dump'
        path.write_text(content)
        return 'dumpsys() { cat ' + shlex.quote(str(path)) + '; }'

    def test_android17_legacy_native_root_uses_first_active_package_block(self):
        dump = textwrap.dedent('''
            Packages:
              Package [com.miui.home] (active):
                codePath=/data/app/~~current/com.miui.home-code
                legacyNativeLibraryDir=/data/app/~~current/com.miui.home-code/lib
                primaryCpuAbi=arm64-v8a
                secondaryCpuAbi=null
            Hidden system packages:
              Package [com.miui.home] (factory):
                legacyNativeLibraryDir=/product/priv-app/MiuiHome/lib
                primaryCpuAbi=arm64-v8a
        ''')
        result = self.shell('native_app_target com.miui.home libflutter.so', overrides=self.package_dump(dump))
        self.assertEqual(result.stdout.strip(), '/data/app/~~current/com.miui.home-code/lib/arm64/libflutter.so')

    def test_android17_factory_and_pad_legacy_native_roots(self):
        for directory in ('/product/app/MIUIWeather/lib', '/product/priv-app/VoiceAssist/lib',
                          '/data/app-lib/MIUIWeather'):
            dump = f'Package [com.miui.weather2] (active):\n  legacyNativeLibraryDir={directory}\n  primaryCpuAbi=arm64-v8a\n'
            with self.subTest(directory=directory):
                result = self.shell('native_app_target com.miui.weather2 libflutter.so', overrides=self.package_dump(dump))
                self.assertEqual(result.stdout.strip(), directory + '/arm64/libflutter.so')

    def test_explicit_native_directory_is_not_suffixed_twice(self):
        dump = ('Package [com.miui.home] (active):\n'
                '  nativeLibraryDir=/data/app/example/lib/arm64\n'
                '  legacyNativeLibraryDir=/data/app/example/lib\n  primaryCpuAbi=arm64-v8a\n')
        result = self.shell('native_app_target com.miui.home libflutter.so', overrides=self.package_dump(dump))
        self.assertEqual(result.stdout.strip(), '/data/app/example/lib/arm64/libflutter.so')

    def test_legacy_native_root_rejects_missing_null_and_incompatible_abi(self):
        for abi in ('', 'null', 'armeabi-v7a', 'x86_64'):
            dump = 'Package [com.miui.home] (active):\n  legacyNativeLibraryDir=/data/app/example/lib\n'
            if abi:
                dump += f'  primaryCpuAbi={abi}\n'
            with self.subTest(abi=abi):
                result = self.shell('native_app_target com.miui.home libflutter.so',
                                    overrides=self.package_dump(dump), check=False)
                self.assertNotEqual(result.returncode, 0)

    def test_ambiguous_native_fields_and_null_active_root_are_not_borrowed(self):
        dumps = [
            ('  nativeLibraryDir=/data/app/one/lib/arm64\n'
             '  nativeLibraryDir=/data/app/two/lib/arm64\n'),
            ('  nativeLibraryDir=/data/app/one/lib/arm64\n'
             '  legacyNativeLibraryDir=/data/app/two/lib\n  primaryCpuAbi=arm64-v8a\n'),
            ('  legacyNativeLibraryDir=null\n  primaryCpuAbi=arm64-v8a\n'
             'Package [com.miui.home] (factory):\n'
             '  legacyNativeLibraryDir=/product/priv-app/MiuiHome/lib\n  primaryCpuAbi=arm64-v8a\n'),
            ('  nativeLibraryDir=null\n  legacyNativeLibraryDir=/data/app/example/lib\n  primaryCpuAbi=arm64-v8a\n'),
        ]
        for fields in dumps:
            result = self.shell('native_app_target com.miui.home libflutter.so',
                                overrides=self.package_dump('Package [com.miui.home] (active):\n' + fields), check=False)
            self.assertNotEqual(result.returncode, 0)

    def test_app_requires_matching_signed_native_code(self):
        _, overrides = self.app(b'different embedded native code')
        self.shell('native_apply_target app fixture "" com.miui.home libtest.so late', overrides=overrides)
        self.assertIn('|skipped|apk-native-code-mismatch\n', (self.module / 'state/status.tsv').read_text())
        self.assertEqual(self.target.read_bytes(), self.original)

    def test_unzip_success_with_empty_output_skips_unavailable_apk_entry(self):
        apk, overrides = self.app()
        original_apk = apk.read_bytes()
        self.target.unlink()
        overrides += textwrap.dedent('''
            native_ns() {
                pid=$1; shift
                [ "$2" != unzip ] || return 0
                "$BB" nsenter -t "$pid" -m -- "$@"
            }
            native_restore_missing() { echo forbidden-publication; return 1; }
        ''')
        result = self.shell('native_apply_target app fixture "" com.miui.home libtest.so late', overrides=overrides)
        self.assertNotIn('forbidden-publication', result.stdout)
        self.assertIn('|skipped|apk-native-entry-unavailable\n', (self.module / 'state/status.tsv').read_text())
        self.assertFalse(self.target.exists())
        self.assertFalse(list((self.module / 'cache').glob('apk-entry.next.*')))
        self.assertEqual(apk.read_bytes(), original_apk)

    def test_missing_private_native_restores_original_without_changing_apk(self):
        apk, overrides = self.app()
        original_apk = apk.read_bytes()
        self.target.unlink()
        overrides += '\nnative_private_target() { native_path "$1"; }'
        overrides += '\nnative_mount() { echo "$2"; return 0; }'
        result = self.shell('NATIVE_CATALOG_HASH=test; native_apply_target app fixture "" com.miui.home libtest.so late', overrides=overrides)
        self.assertEqual(self.target.read_bytes(), self.original)
        self.assertEqual(apk.read_bytes(), original_apk)
        self.assertEqual(Path(result.stdout.strip()).read_bytes(), self.after)
        self.assertFalse(list(self.root.glob('*.hyperos-native-original.*')))

    def test_missing_private_native_never_overwrites_raced_file(self):
        apk, overrides = self.app()
        original_apk = apk.read_bytes()
        self.target.unlink()
        entry = self.module / 'cache/original-entry'
        entry.write_bytes(self.original)
        overrides += '\nnative_private_target() { native_path "$1"; }'
        # A competing extraction commits just after stable package checks.
        overrides += '\nnative_active_apk() { printf raced > ' + shlex.quote(str(self.target)) + '; printf "%s\\n" ' + shlex.quote(str(apk)) + '; }'
        command = 'native_restore_missing ' + ' '.join(shlex.quote(str(value)) for value in
                    (self.target, entry, digest(self.original), apk, digest(original_apk),
                     'com.miui.home', 'libtest.so', 'fixture'))
        result = self.shell(command, overrides=overrides, check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(self.target.read_bytes(), b'raced')
        self.assertEqual(apk.read_bytes(), original_apk)

    def test_missing_private_native_cleans_temporary_on_label_failure(self):
        apk, overrides = self.app()
        original_apk = apk.read_bytes()
        self.target.unlink()
        entry = self.module / 'cache/original-entry'
        entry.write_bytes(self.original)
        overrides += '\nnative_private_target() { native_path "$1"; }'
        (self.bin / 'chcon').write_text('#!/bin/sh\nexit 1\n')
        command = 'native_restore_missing ' + ' '.join(shlex.quote(str(value)) for value in
                    (self.target, entry, digest(self.original), apk, digest(original_apk),
                     'com.miui.home', 'libtest.so', 'fixture'))
        result = self.shell(command, overrides=overrides, check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertFalse(self.target.exists())
        self.assertFalse(list(self.root.glob('*.hyperos-native-original.*')))
        self.assertEqual(apk.read_bytes(), original_apk)

    def test_private_restore_rejects_alias_and_missing_parent(self):
        apk, overrides = self.app()
        entry = self.module / 'cache/original-entry'
        entry.write_bytes(self.original)
        self.target.unlink()
        unrelated = self.root / 'unrelated'
        unrelated.write_bytes(b'preserve me')
        self.target.symlink_to(unrelated)
        overrides += '\nnative_private_target() { native_path "$1"; }'
        command = 'native_restore_missing ' + ' '.join(shlex.quote(str(value)) for value in
                    (self.target, entry, digest(self.original), apk, digest(apk.read_bytes()),
                     'com.miui.home', 'libtest.so', 'fixture'))
        result = self.shell(command, overrides=overrides, check=False)
        self.assertEqual(result.returncode, 3)
        self.assertEqual(unrelated.read_bytes(), b'preserve me')
        self.target.unlink()
        missing = self.root / 'not-published/libtest.so'
        result = self.shell(command.replace(shlex.quote(str(self.target)), shlex.quote(str(missing))),
                            overrides=overrides, check=False)
        self.assertEqual(result.returncode, 3)
        self.assertFalse(missing.parent.exists())

    def test_stable_app_receipt_does_not_restart_or_remount_on_unrelated_update(self):
        _, overrides = self.app()
        marker = self.root / 'mounts'
        overrides += '\nnative_mount() { cp "$2" "$1"; echo mounted >> ' + shlex.quote(str(marker)) + '; }'
        self.shell('NATIVE_CATALOG_HASH=test; native_apply_target app fixture "" com.miui.home libtest.so late; '
                   'native_apply_target app fixture "" com.miui.home libtest.so late', overrides=overrides)
        self.assertEqual(marker.read_text(), 'mounted\n')

    def test_package_replacement_during_patch_refuses_bind(self):
        apk, overrides = self.app()
        counter = self.root / 'pm-count'
        counter.write_text('0')
        overrides += '\nnative_active_apk() { count=$(cat ' + shlex.quote(str(counter)) + '); count=$((count+1)); '
        overrides += 'echo "$count" > ' + shlex.quote(str(counter)) + '; '
        overrides += 'if [ "$count" -gt 1 ]; then echo /data/app/replaced/base.apk; else printf "%s\\n" ' + shlex.quote(str(apk)) + '; fi; }'
        overrides += '\nnative_mount() { echo forbidden; return 0; }'
        result = self.shell('native_apply_target app fixture "" com.miui.home libtest.so late', overrides=overrides)
        self.assertNotIn('forbidden', result.stdout)
        self.assertIn('|skipped|package-changing\n', (self.module / 'state/status.tsv').read_text())
        self.assertEqual(self.target.read_bytes(), self.original)

    def test_unknown_code_skips_only_its_feature(self):
        self.target.write_bytes(b'unknown')
        result = self.shell('native_apply_target system fixture ' + shlex.quote(str(self.target)) + ' "" libtest.so early',
                            overrides=self.safe_paths())
        self.assertEqual(result.returncode, 0)
        self.assertIn('|skipped|unsupported-elf\n', (self.module / 'state/status.tsv').read_text())
        self.assertEqual(self.target.read_bytes(), b'unknown')

    def test_composer_then_rear_terminal_output_is_not_regressed(self):
        final = self.after.replace(b'tail', b'done')
        self.profile('rear', 'rear', self.after, final,
                     [(len(self.after) - 4, b'tail', b'done')], append=True)
        with (self.module / 'targets.tsv').open('a') as output:
            output.write(f'early|system|rear|{self.target}||libtest.so\n')
        self.target.write_bytes(final)
        self.shell('native_apply_target system fixture ' + shlex.quote(str(self.target)) + ' "" libtest.so early',
                   overrides=self.safe_paths())
        self.assertIn('|ready|already-patched\n', (self.module / 'state/status.tsv').read_text())
        self.assertEqual(self.target.read_bytes(), final)

    def test_only_module_cache_mounts_are_owned(self):
        info = self.proc / '1/mountinfo'
        info.write_text(f'1 0 1:1 {self.module}/cache/good.so {self.target} rw - ext4 disk rw\n')
        self.shell('native_owns_mount 1 ' + shlex.quote(str(self.target)))
        info.write_text(f'1 0 1:1 /adb/modules/another/cache/good.so {self.target} rw - ext4 disk rw\n')
        self.shell('! native_owns_mount 1 ' + shlex.quote(str(self.target)))
        info.write_text(f'1 0 1:1 {self.module}/cache/good.so {self.target} rw - ext4 disk rw\n'
                        f'2 1 1:1 /adb/modules/another/cache/good.so {self.target} rw - ext4 disk rw\n')
        self.shell('! native_owns_mount 1 ' + shlex.quote(str(self.target)))

    def test_mount_failure_rolls_back_new_namespaces_only(self):
        for pid in ('2', '3'):
            (self.proc / pid).mkdir()
        states = self.root / 'namespace-state'
        states.mkdir()
        for pid, checksum in (('1', digest(self.original)), ('2', digest(self.original)),
                              ('3', digest(self.after))):
            (states / pid).write_text(checksum + '\n')
        marker = self.root / 'mount-calls'
        overrides = self.safe_paths() + '\nSTATE=' + shlex.quote(str(states)) + '\n'
        overrides += 'MARKER=' + shlex.quote(str(marker)) + '\n'
        overrides += 'native_pids() { printf "1\\n2\\n3\\n"; }\n'
        overrides += 'native_ns_hash() { cat "$STATE/$1"; }\n'
        overrides += 'native_owns_mount() { [ "$(cat "$STATE/$1")" = ' + digest(self.after) + ' ]; }\n'
        overrides += 'native_mount_flags() { return 0; }\n'
        overrides += textwrap.dedent('''
            native_ns() {
                pid=$1; shift 2
                case "$*" in
                    'mount -o bind '*)
                        echo "bind:$pid" >> "$MARKER"
                        [ "$pid" != 2 ] || return 1
                        printf '%s\\n' FINAL_HASH > "$STATE/$pid" ;;
                    'mount -o remount,bind,ro,nosuid,nodev '*) echo "readonly:$pid" >> "$MARKER" ;;
                    'umount '*) echo "rollback:$pid" >> "$MARKER"; printf '%s\\n' INITIAL_HASH > "$STATE/$pid" ;;
                    *) return 1 ;;
                esac
            }
        ''').replace('FINAL_HASH', digest(self.after)).replace('INITIAL_HASH', digest(self.original))
        command = 'native_mount ' + ' '.join(map(shlex.quote, (str(self.target), str(self.target),
                   '', digest(self.original), digest(self.after))))
        result = self.shell(command, overrides=overrides, check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(marker.read_text(), 'bind:1\nreadonly:1\nbind:2\nrollback:1\n')
        self.assertEqual((states / '1').read_text().strip(), digest(self.original))
        self.assertEqual((states / '3').read_text().strip(), digest(self.after))

    def test_disable_and_remove_flags_and_feature_choice(self):
        (self.module / 'disable').touch()
        self.shell('native_blocked')
        (self.module / 'disable').unlink()
        (self.module / 'remove').touch()
        self.shell('native_blocked')
        (self.module / 'remove').unlink()
        (self.module / 'features.disabled').write_text('fixture\n')
        self.shell('native_apply_target system fixture ' + shlex.quote(str(self.target)) + ' "" libtest.so early',
                   overrides=self.safe_paths())
        self.assertIn('|disabled|user-choice\n', (self.module / 'state/status.tsv').read_text())
        self.assertEqual(self.target.read_bytes(), self.original)

    def test_status_updates_are_atomic_and_replace_the_same_key(self):
        self.shell('native_status fixture target skipped unknown; native_status fixture target ready verified')
        self.assertEqual((self.module / 'state/status.tsv').read_text(), 'fixture|target|ready|verified\n')
        self.assertFalse(list((self.module / 'state').glob('*.next.*')))

    def test_late_service_never_mounts_early_preloaded_targets(self):
        overrides = self.safe_paths() + '\nnative_mount() { echo forbidden-mount; return 1; }'
        result = self.shell('native_reconcile late', overrides=overrides)
        self.assertNotIn('forbidden-mount', result.stdout)
        self.assertIn('|pending|reboot-required\n', (self.module / 'state/status.tsv').read_text())

    def test_failed_owned_detach_never_rebinds_from_a_masked_source(self):
        overrides = self.safe_paths() + '\nnative_detach() { return 1; }\nnative_apply_target() { echo forbidden-rebind; }'
        result = self.shell('native_reconcile early', overrides=overrides)
        self.assertNotIn('forbidden-rebind', result.stdout)
        self.assertIn('|failed|owned-detach\n', (self.module / 'state/status.tsv').read_text())

    def test_uninstalled_app_receipt_is_retired_without_removing_original(self):
        (self.module / 'targets.tsv').write_text('late|app|fixture||com.miui.home|libtest.so\n')
        receipt = self.module / 'state/fixture-com.miui.home-libtest.so.receipt'
        receipt.write_text(f'catalog|/data/app/example/base.apk|hash|{self.target}|{digest(self.after)}\n')
        overrides = self.safe_paths() + '\nnative_resolve_target() { return 1; }\n'
        overrides += 'native_detach() { echo "detached:$1"; }\n'
        overrides += 'pm() { return 1; }; dumpsys() { return 1; }'
        result = self.shell('native_reconcile late', overrides=overrides)
        self.assertIn(f'detached:{self.target}\n', result.stdout)
        self.assertFalse(receipt.exists())
        self.assertEqual(self.target.read_bytes(), self.original)
        self.assertIn('|skipped|retired-native-path\n', (self.module / 'state/status.tsv').read_text())

    def test_cleanup_uses_old_app_receipt_when_package_is_unavailable(self):
        (self.module / 'targets.tsv').write_text('late|app|fixture||com.miui.home|libtest.so\n')
        receipt = self.module / 'state/fixture-com.miui.home-libtest.so.receipt'
        receipt.write_text(f'catalog|/data/app/example/base.apk|hash|{self.target}|{digest(self.after)}\n')
        overrides = self.safe_paths() + '\nnative_resolve_target() { return 1; }\n'
        overrides += 'native_detach() { echo "detached:$1"; }'
        result = self.shell('native_cleanup', overrides=overrides)
        self.assertEqual(result.stdout, f'detached:{self.target}\n')
        self.assertTrue(receipt.exists())
        self.assertEqual(self.target.read_bytes(), self.original)
        self.assertIn('|disabled|restart-for-loaded-code\n', (self.module / 'state/status.tsv').read_text())

    def test_failed_retired_app_detach_blocks_rebinding(self):
        (self.module / 'targets.tsv').write_text('late|app|fixture||com.miui.home|libtest.so\n')
        receipt = self.module / 'state/fixture-com.miui.home-libtest.so.receipt'
        receipt.write_text(f'catalog|/data/app/example/base.apk|hash|{self.target}|{digest(self.after)}\n')
        overrides = self.safe_paths() + '\nnative_resolve_target() { return 1; }\n'
        overrides += 'native_detach() { return 1; }\n'
        overrides += 'native_apply_target() { echo forbidden-rebind; }'
        result = self.shell('native_reconcile late', overrides=overrides)
        self.assertNotIn('forbidden-rebind', result.stdout)
        self.assertTrue(receipt.exists())
        self.assertIn('|failed|prior-app-detach\n', (self.module / 'state/status.tsv').read_text())

    def test_loaded_old_inode_requires_reboot_instead_of_reporting_ready(self):
        self.target.write_bytes(self.after)
        (self.proc / '1/maps').write_text(f'1000-2000 r-xp 00000000 fe:38 1 {self.target}\n')
        self.shell('native_apply_target system fixture ' + shlex.quote(str(self.target)) + ' "" libtest.so early',
                   overrides=self.safe_paths())
        self.assertIn('|pending|reboot-required\n', (self.module / 'state/status.tsv').read_text())

    def test_loaded_same_inode_on_different_device_is_stale(self):
        maps = self.proc / '1/maps'
        overrides = 'native_ns() { echo "65080 123"; }'
        maps.write_text(f'1000-2000 r-xp 00000000 fe:39 123 {self.target}\n')
        self.shell('native_loaded_stale ' + shlex.quote(str(self.target)), overrides=overrides)
        maps.write_text(f'1000-2000 r-xp 00000000 fe:38 123 {self.target}\n')
        self.shell('! native_loaded_stale ' + shlex.quote(str(self.target)), overrides=overrides)

    def test_hwui_preload_policy_is_early_and_requires_verified_output(self):
        self.profile('hwui', 'hwui', self.original, self.after, [(7, b'original', b'patched!')])
        marker = self.root / 'property'
        overrides = 'getprop() { [ "$1" != ro.zygote.disable_gl_preload ] || cat ' + shlex.quote(str(marker)) + '; }\n'
        overrides += 'native_resetprop() { echo "$2" > ' + shlex.quote(str(marker)) + '; }'
        marker.write_text('1\n')
        self.shell('native_hwui_policy ' + shlex.quote(str(self.target)) + ' late', overrides=overrides)
        self.assertEqual(marker.read_text(), '1\n')
        self.shell('! native_hwui_policy ' + shlex.quote(str(self.target)) + ' early', overrides=overrides)
        self.assertEqual(marker.read_text(), '1\n')
        self.target.write_bytes(self.after)
        self.shell('native_hwui_policy ' + shlex.quote(str(self.target)) + ' early', overrides=overrides)
        self.assertEqual(marker.read_text(), '0\n')

    def test_stale_lock_after_reboot_is_recovered(self):
        lock = self.module / 'service.lock'
        lock.mkdir()
        (lock / 'pid').write_text('123\n')
        (lock / 'boot').write_text('prior-boot\n')
        self.shell('sleep() { :; }; native_service_lock "$MODDIR/service.lock"')
        self.assertEqual((lock / 'boot').read_text(), 'test-boot\n')
        self.assertNotEqual((lock / 'pid').read_text(), '123\n')

    def test_empty_crash_lock_is_recovered_and_new_state_is_private(self):
        lock = self.module / 'service.lock'
        lock.mkdir(mode=0o777)
        (lock / 'pid').touch()
        (lock / 'boot').touch()
        self.shell('sleep() { :; }; native_service_lock "$MODDIR/service.lock"')
        self.assertTrue((lock / 'pid').read_text().strip().isdigit())
        self.assertEqual((lock / 'boot').read_text(), 'test-boot\n')
        self.assertEqual(lock.stat().st_mode & 0o777, 0o700)
        self.assertEqual((lock / 'pid').stat().st_mode & 0o777, 0o600)
        self.assertEqual((self.module / 'service.lock.guard').stat().st_mode & 0o777, 0o600)
        self.shell('mkdir "$MODDIR/new-private-state"; umask')
        self.assertEqual((self.module / 'new-private-state').stat().st_mode & 0o777, 0o700)

    def test_missing_owner_fields_are_recovered_after_grace(self):
        lock = self.module / 'service.lock'
        lock.mkdir()
        self.shell('sleep() { :; }; native_service_lock "$MODDIR/service.lock"')
        self.assertEqual((lock / 'boot').read_text(), 'test-boot\n')

    def test_live_service_acquiring_empty_lock_is_preserved(self):
        lock = self.module / 'service.lock'
        lock.mkdir()
        (lock / 'pid').touch()
        (lock / 'boot').touch()
        owner = self.proc / '123'
        owner.mkdir()
        overrides = 'sleep() { printf "%s\\000%s\\000" /system/bin/sh "$MODDIR/service.sh" > "$PROC/123/cmdline"; }'
        result = self.shell('native_service_lock "$MODDIR/service.lock"', overrides=overrides, check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual((lock / 'pid').read_bytes(), b'')
        self.assertEqual((lock / 'boot').read_bytes(), b'')

    def test_lock_recovery_rejects_aliases_and_unexpected_entries(self):
        lock = self.module / 'service.lock'
        lock.mkdir()
        unrelated = self.root / 'unrelated-lock-data'
        unrelated.write_text('preserve')
        (lock / 'pid').symlink_to(unrelated)
        result = self.shell('sleep() { :; }; native_service_lock "$MODDIR/service.lock"', check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(unrelated.read_text(), 'preserve')
        (lock / 'pid').unlink()
        (lock / 'unexpected').write_text('preserve')
        result = self.shell('sleep() { :; }; native_service_lock "$MODDIR/service.lock"', check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual((lock / 'unexpected').read_text(), 'preserve')

    def test_service_exit_cleanup_survives_function_return(self):
        overrides = textwrap.dedent('''
            native_guard() { return 0; }
            native_assets() { return 0; }
            native_reconcile() { :; }
            native_cleanup() { :; }
            sleep() { touch "$MODDIR/disable"; }
        ''')
        result = self.shell('native_service; echo function-returned; test -d "$MODDIR/service.lock"', overrides=overrides)
        self.assertEqual(result.stdout, 'function-returned\n')
        self.assertFalse((self.module / 'service.lock').exists())

    def test_service_lock_release_preserves_new_owner_receipt(self):
        self.shell('native_service_lock "$MODDIR/service.lock"; '
                   'printf "999\\n" > "$MODDIR/service.lock/pid"; '
                   'printf "another-owner-boot\\n" > "$MODDIR/service.lock/boot"; '
                   'native_service_release')
        lock = self.module / 'service.lock'
        self.assertTrue(lock.is_dir())
        self.assertEqual((lock / 'pid').read_text(), '999\n')
        self.assertEqual((lock / 'boot').read_text(), 'another-owner-boot\n')

    def test_service_lease_preserves_concurrently_acquired_lock(self):
        ready = self.root / 'owner-ready'
        release = self.root / 'owner-release'
        script = ('MODDIR=' + shlex.quote(str(self.module)) + '\n. "$MODDIR/runtime.sh"\n'
                  'native_service_lock "$MODDIR/service.lock" || exit 1\n'
                  'touch ' + shlex.quote(str(ready)) + '\n'
                  'while [ ! -e ' + shlex.quote(str(release)) + ' ]; do sleep 0.01; done\n'
                  'native_service_release\n')
        owner = subprocess.Popen(['sh', '-c', script], env=self.environment, text=True,
                                 stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        self.addCleanup(lambda: owner.kill() if owner.poll() is None else None)
        import time
        deadline = time.monotonic() + 5
        while not ready.exists() and owner.poll() is None and time.monotonic() < deadline:
            time.sleep(0.01)
        self.assertTrue(ready.exists())
        before = (self.module / 'service.lock/pid').read_bytes()
        result = self.shell('native_service_lock "$MODDIR/service.lock"', check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual((self.module / 'service.lock/pid').read_bytes(), before)
        release.touch()
        _, stderr = owner.communicate(timeout=5)
        self.assertEqual(owner.returncode, 0, stderr)
        self.assertFalse((self.module / 'service.lock').exists())

    def test_service_reconciles_only_on_debounced_tokens_and_stops_when_disabled(self):
        token = self.root / 'token'
        token.write_text('original\n')
        overrides = textwrap.dedent('''
            native_guard() { return 0; }
            native_assets() { return 0; }
            native_service_lock() { return 0; }
            native_reconcile() { echo "$1"; }
            native_cleanup() { echo cleanup; }
            native_package_token() { cat "$TOKEN"; }
            counter=0
            sleep() {
                counter=$((counter + 1))
                case "$counter" in 2) echo changed > "$TOKEN";; 4) touch "$MODDIR/disable";; esac
            }
        ''')
        result = self.shell('TOKEN=' + shlex.quote(str(token)) + '\nnative_service', overrides=overrides)
        self.assertEqual(result.stdout, 'late\nlate\ncleanup\n')

    def test_real_flutter_byte_sites_match_python_patcher_when_fixture_exists(self):
        path = os.environ.get('HYPEROS_AVD_FLUTTER18_ARTIFACT')
        if not path or not Path(path).is_file():
            self.skipTest('Optional verified proprietary Flutter fixture is unavailable.')
        sys.path.insert(0, str(REPO / 'scripts'))
        from patch_flutter import patch, profile
        original = Path(path).read_bytes()
        before, selected = profile(original)
        sites = [(offset, bytes.fromhex(old), bytes.fromhex(new)) for offset, old, new in selected['sites']]
        expected = patch(original)
        self.profile('flutter', 'flutter', original, expected, sites)
        self.target.write_bytes(original)
        result = self.shell('native_prepare ' + shlex.quote(str(self.target)) + ' flutter ' + before)
        self.assertEqual(Path(result.stdout.strip()).read_bytes(), expected)


if __name__ == '__main__':
    unittest.main()
